[build]
  command = "pnpm install && pnpm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/microservices", 
    "@nestjs/websockets",
    "@prisma/client"
  ]
  included_files = [
    "node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**",
    "node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/**"
  ]

[functions.api]
  timeout = 30
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200