[build]
  command = "pnpm install && pnpm run netlify-build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@prisma/client",
    "prisma",
    "argon2",
    "@phc/format",
    "node-addon-api", 
    "node-gyp-build",
    "ioredis",
    "mqtt",
    "@nestjs/platform-socket.io",
    "@grpc/grpc-js",
    "nats",
    "@grpc/proto-loader",
    "amqplib",
    "kafkajs"
  ]
  
  included_files = [
    "node_modules/.prisma/**/*",
    "node_modules/argon2/**/*",
    "node_modules/@phc/**/*",
    "node_modules/node-addon-api/**/*",
    "node_modules/node-gyp-build/**/*",
    "dist/**/*"
  ]

[functions.api]
  timeout = 30
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200