[build]
  command = "pnpm install && pnpm run netlify-build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@prisma/client",
    "prisma",
    "argon2",
    "@nestjs/microservices",
    "@nestjs/websockets",
    "@nestjs/platform-socket.io",
    "ioredis",
    "kafkajs",
    "@grpc/grpc-js",
    "@grpc/proto-loader",
    "mqtt",
    "nats"
  ]
  
  included_files = [
    "node_modules/.prisma/**/*",
    "node_modules/argon2/**/*",
    "node_modules/@phc/**/*"
  ]

[functions.api]
  timeout = 30
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200