[build]
  command = "pnpm install && pnpm run netlify-build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/microservices", 
    "@nestjs/websockets",
    "@prisma/client",
    "prisma",
    "argon2",
    "@phc/format",
    "cross-env", 
    "node-addon-api",
    "node-gyp-build"
  ]
  
  included_files = [
    "node_modules/argon2/**/*",
    "node_modules/@phc/**/*",
    "node_modules/cross-env/**/*",
    "node_modules/node-addon-api/**/*", 
    "node_modules/node-gyp-build/**/*",
    "node_modules/.prisma/**/*"
  ]

[functions.api]
  timeout = 30
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200