[build]
  command = "npx pnpm install --dangerously-allow-all-builds && PRISMA_CLI_BINARY_TARGETS=rhel-openssl-1.0.x npx prisma generate && npx nest build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@nestjs/microservices", "@nestjs/websockets", "@prisma/client", ".prisma/client"]
  included_files = ["node_modules/.prisma/**", "node_modules/@prisma/client/**"]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200