[build]
  command = "pnpm install && pnpm run netlify-build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    # NestJS Framework
    "@nestjs/microservices", 
    "@nestjs/websockets",
    
    # Database & ORM
    "@prisma/client",
    "@prisma/engines", 
    "@prisma/adapter-pg",
    "prisma",
    
    # PostgreSQL Driver & Dependencies  
    "pg",
    "pg-cloudflare",
    "pg-connection-string", 
    "pg-pool",
    "pg-protocol",
    "pg-types",
    "pgpass",
    
    # Argon2 Password Hashing & Dependencies
    "argon2",
    "@phc/format",
    "cross-env", 
    "node-addon-api",
    "node-gyp-build",
    
    # JWT & Authentication
    "jsonwebtoken",
    "passport",
    "passport-jwt",
    "passport-strategy"
  ]
  
  included_files = [
    # Native modules and their dependencies
    "node_modules/argon2/**/*",
    "node_modules/@phc/**/*",
    "node_modules/cross-env/**/*",
    "node_modules/node-addon-api/**/*", 
    "node_modules/node-gyp-build/**/*",
    
    # PostgreSQL driver files
    "node_modules/pg/**/*",
    "node_modules/pg-*/**/*",
    "node_modules/pgpass/**/*",
    
    # Prisma binaries and generated client
    "node_modules/.prisma/**/*",
    "node_modules/@prisma/**/*",
    "node_modules/prisma/**/*"
  ]

[functions.api]
  timeout = 30
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200