[build]
  command = "pnpm install && pnpm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-1.0.x"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@nestjs/microservices", "@nestjs/websockets", "@prisma/client", ".prisma/client"]
  included_files = [
  "node_modules/.pnpm/@prisma+client*/node_modules/@prisma/client/**",
  "node_modules/.pnpm/@prisma+client*/node_modules/.prisma/**",
  "node_modules/@prisma/client/**",
  "node_modules/.prisma/**"
]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200