[build]
  command = "npx pnpm install npx pnpm approve-builds && npx prisma generate && npx nest build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@nestjs/microservices", "@nestjs/websockets"]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200